spring.application.name=backend
server.port=8082
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8888/realms/tutorial-realm
spring.datasource.url=jdbc:postgresql://localhost:5432/tutorial
spring.datasource.username=tutorial
spring.datasource.password=tutorial
spring.jpa.hibernate.ddl-auto=update